#docker-composeで使用するバージョン
version: '3.8'

services:
 #サービスの名前
  centos:
    build: .
    tty: true
    command: /sbin/init
    ports:
      - 8080:80
    volumes:
      - ./web:/var/www/html
    privileged: true
